version: '3.4'

services:
  planningboard:
    image: planningboard
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    depends_on:
      - sqlserver
    environment:
      DBServer: "sqlserver"
      DBPort: 14331
      DBUser: "sa"
      DBPassword: "1Secure*Password1"
      Database: "planningboard"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "1Secure*Password1"
      ACCEPT_EULA: "Y"
    volumes:
      - ./sqlvolume/data:/var/opt/mssql/data
      - ./sqlvolume/log:/var/opt/mssql/log
      - ./sqlvolume/secrets:/var/opt/mssql/secrets
    ports:
    - "14331:1433"
