# /docker-compose-integration.yml
version: '3.4'

services:
  integration:
    build:
      context: .
      dockerfile: Integration.Dockerfile
    entrypoint: dotnet test -l:"console;verbosity=detailed"
    depends_on:
    #   - web
      - db
#   web:
#     build: .
#     ports:
#       - 5000:5000
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Integration
#     #entrypoint: dotnet /app/PlanningBoard.Api.dll
#     depends_on:
#       - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      SA_PASSWORD: "1Secure*Password1"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - ./sqlvolume/data:/var/opt/mssql/data
      - ./sqlvolume/log:/var/opt/mssql/log
      - ./sqlvolume/secrets:/var/opt/mssql/secrets
    ports:
    - "14331:1433"